version: '3'
services:
  db:
    image: artifactory.pegadaian.co.id:8084/postgres:9.6-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  db_test:
    container_name: go-boiler-plate-db-test
    image: artifactory.pegadaian.co.id:8084/postgres:9.6-alpine
    ports:
      - 5433:5432 # you need to change this into `{unique port}:5432`
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  test_app:
    container_name: go-boiler-plate-test-app
    build:
      context: ./
      dockerfile: deployment/test.Dockerfile
    env_file: .env.test
    depends_on:
      - db_test

  dev_app:
    build:
      context: ./
      dockerfile: deployment/dev.Dockerfile
    ports:
      - 8081:8081
    env_file:
      - .env

  app:
    build:
      context: ./
      dockerfile: deployment/Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env